version: '3.7'

services:

  web:
    build: .
    ports:
      - "8000:3000"
    volumes:
      - .:/usr/src/app
    env_file:
      - .envdir/development/database
      - .envdir/development/web
    depends_on:
      - database

    # for binding.pry tty + stdin_open
    tty: true
    stdin_open: true

  database:
    image: postgres:12.2
    env_file:
      - .envdir/development/database
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
